version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker" # Location of package manifests
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
